name: colony_counter
description: "Colony Counter App Project"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  widget_zoom: ^0.0.4
  image_picker: ^1.1.2
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
